# **Python: Getting Started**

## Tính toán đơn giản

Ngoài tất cả những thứ phức tạp hơn bạn có thể làm bằng Python, nó cũng hữu ích để hoàn thành các phép toán đơn giản

**Cộng và trừ**

Cộng một số lại với nhau sẽ như thế này

In [1]:
1 + 1

2

Chú ý rằng bạn không cần phải bao gồm **=** để chạy được mã code

Trừ các số với nhau sẽ như thế này

In [2]:
2 - 1

1

**Phép chia**

Chia một số sẽ như thế này

In [3]:
4 / 2

2.0

Hãy nhớ rằng Python sẽ trả về lỗi nếu bạn chia cho 0!

**Tìm số dư**

Thực hiện chia lấy phần dư sẽ như thế này

In [4]:
5 % 2

1

**Phép nhân**

Nhân một số sẽ như thế này

In [5]:
4 * 2

8

Thêm **số mũ** cho một số sẽ như thế này

In [6]:
4 ** 2

16

## Thứ tự hoạt động

Python cũng có thứ tự hoạt động cụ thể:

    Dấu ngoặc đơn, Số mũ, Phép nhân, Phép cộng và phép trừ

In [7]:
(6 + 4) + 4

14

Mọi thứ trở nên phức tạp hơn khi chúng ta thêm nhiều số hạng hơn vào phương trình, nhưng nguyên tắc vẫn như cũ

In [8]:
(((5**3 + 7) * 4) / 16 + 9 - 2)

40.0

## Kiểu dữ liệu

**Boolean** (bool):

    Bất kỳ dữ liệu nào đều được biểu thị là Đúng hoặc Sai.
    Được sử dụng khi so sánh hai giá trị.
    Ví dụ: nhập vào 10 > 9, Python sẽ trả về 'True'

**Chuỗi** (str):

    Dữ liệu liên quan đến văn bản - chữ cái, số hoặc ký tự đặc biệt.
    Các chuỗi được đặt trong dấu ngoặc kép đơn hoặc ngoặc kép: "string-1" hoặc 'string-2'.

**Numeric** (int, float, complex):

    Dữ liệu có thể được thể hiện bằng số.
    Một số nguyên, hoặc int là số nguyên dương hoặc âm, không có số thập phân, có độ dài không giới hạn.
    Số thập phân, hoặc số thực là một số dương hoặc âm, chứa một hoặc nhiều số thập phân: 12.01.
    Số phức là các số ảo, được ký hiệu hằng j: (3 + 6j)

**Trình tự** (list, tuple, set):

    Dữ liệu là một tập hợp các mục rời rạc.
    - A list là một tập hợp được sắp xếp và có thể thay đổi. Nó được chỉ định bằng cách sử dụng dấu ngoặc vuông [] và các mục có thể thuộc các kiểu dữ liệu khác nhau: ["red",1,1.03,1]
    - Bộ tuple là một bộ sưu tập được sắp xếp theo thứ tự và không thể thay đổi. Nó được chỉ định bằng cách sử dụng dấu ngoặc đơn (): ("read",1,1.03,1)
    - Set là một tập hợp không có thứ tự, không thể thay đổi và không cho phép các mục trùng lặp. Nó chỉ định bằng cách sử dụng dấu ngoặc nhọn {}: {"red",1,1.03}

**Mapping** (dict):

    Dictionaries lưu trữ dữ liệu theo cặp key-value. Chúng được chỉ định bằng cách sử dụng dấu ngoặc nhọn {}, giống như một tập hợp, nhưng lưu ý rằng các key-value được liên kết với nhau bằng dấu hai chấm:.
    Mỗi cặp được phân tách với cặp tiếp theo bằng dấu phẩy,.
    dict1 = {
        "bo_phan": "quindio",
        "loai_tai_san": "nha",
        "gia_tien": 330899.98
    }

**Binary (Nhị phân)** (byte, bytearray, memoryview):

    Được sử dụng để thao tác và hiển thị dữ liệu nhị phân. Đó là dữ liệu có thể được hiển thị bằng các số nguyên được biểu diễn với cơ số 2.
    Không giống các kiểu dữ liệu khác được mô tả ở trên, kiểu nhị phân không phải là kiểu mọi người có thể đọc được.

## **List**

Trong Python, list là một tập hợp dữ liệu lưu trữ nhiều mục trong một biến duy nhất. Các mục này phải được đặt hàng, có thể thay đổi và có thể được sao chép. Một list có thể lưu trữ dữ liệu của nhiều loại; không phải tất cả các mục trong danh sách cần phải cùng một loại.

## **Tạo list**

List có thể dài hoặc ngắn tùy thích. Hãy tạo một list ngắn dựa trên dữ liệu từ thị trường bất động sản Vietnam để cung cấp điều gì đó để làm việc.

List được viết bằng dấu ngoặc vuông. Mã cho một danh sách ngắn hiển thị giá nhà bằng VNĐ trông như sau:

In [2]:
price_vnd = [1235618000, 2123520000, 3216523000]
price_vnd

[1235618000, 2123520000, 3216523000]

## **Làm việc với lists**

Sau khi tạo list, có thể truy cập bất kỳ mục nào trong list bằng cách tham khảo số index (chỉ mục) của mục đó. Trong Python, mục đầu tiên trong danh sách luôn là 0.

In [3]:
price_vnd[1]

2123520000

#### **Thực hành**

Hãy thử nó cho mình! Tạo và in một list hiển thị diện tích của các ngôi nhà, được gọi là area_m2. Bao gồm các mục 187.0, 82.0 và 235.0.

Nếu chúng ta muốn truy cập một mục ở cuối danh sách, chúng ta có thể sử dụng index phủ định. Trong index phủ định, -1 đề cập đến mục cuối cùng, -2 đến mục thứ hai từ dưới lên, v.v.

**Thực hành**

Hãy thử truy cập vào mục thứ hai trong danh sách area_m2 của bạn.

Hãy thử truy cập vào mục cuối cùng trong cùng một danh sách.

## Thêm phần tử

Bạn có thể thêm một mục vào list đã tồn tại bằng phép nối:

In [4]:
price_vnd.append(55024.86)
price_vnd

[1235618000, 2123520000, 3216523000, 55024.86]

#### **Thực hành**

Thêm mục 195.0 vào list area_m2 của bạn.

## Tổng hợp các mục
Chúng ta có thể tổng hợp các mục trên một list để làm cho việc phân tích list trở nên hữu ích hơn

Ví du: nếu muốn biết tổng giá trị bằng VNĐ của những ngôi nhà trong list price_vnd, có thể sử dụng syntax (cú pháp) **sum**

In [5]:
total_vnd = sum(price_vnd)
total_vnd

6575716024.86

Chúng ta sẽ quan tâm đến giá trị tung bình bằng VNĐ của những ngôi nhà trong cùng list. Để tìm giá trị trung bình, ta dùng syntx 'len' và syntax 'sum'

In [7]:
average_vnd = sum(price_vnd) / len(price_vnd)
average_vnd

1643929006.215

#### **Thực hành**

Hãy thử nó cho mình! Tính tổng diện tích của các ngôi nhà trong list area_m2 của bạn và tìm diện tích trung bình của tất cả các ngôi nhà trong list.

## Zipping

Cuối cùng, có thể hữu ích khi kết hợp - hoặc nén - hai list với nhau.

Ví dụ: muốn tạo một list mới ghép các giá trị trong danh sách price_vnd với danh sách area_m2. Để làm điều đó, sử dụng zip.

In [8]:
area_m2 = [235.0, 130.0, 137.0]

In [9]:
new_list = zip(price_vnd,area_m2)
zipped_list = list(new_list)
zipped_list

[(1235618000, 235.0), (2123520000, 130.0), (3216523000, 137.0)]

    Cách này gọi là trình tạo.

#### **Thực hành**

Hãy thử nó cho mình! Tạo list có tên area_m2 bao gồm các điều khoản 235.0, 130.0 và 137.0, sau đó tạo một list khác có tên price_cop bao gồm các điều khoản 400000000.0, 850000000.0 và 475000000.0. Sau đó nén chúng lại với nhau để tạo một list mới có tên area_price và in kết quả.

## **Python cho các vòng lặp**

Vòng lặp for được sử dụng để thực hiện một tập hợp các câu lệnh cho mỗi mục trong list.

### **Làm việc với for Loops**

Có thể có bao nhiêu câu trong list, nhưng để quản lý được mọi thứ, hãy sử dụng list giá trị bđs ở VN

In [11]:
price_vnd = [1235618000, 2123520000, 3216523000]
price_vnd

[1235618000, 2123520000, 3216523000]

Chúng ta muốn xem từng giá trị trong list, vì vậy sử dụng vòng lặp for

In [12]:
for x in price_vnd:
    print(x)

1235618000
2123520000
3216523000


#### **Thực hành**

Thử với area_m2

In [13]:
for i in area_m2:
    print(i)

235.0
130.0
137.0


## **Dictionary trong Python**

Trong Python, a dictionary là một tập hợp dữ liệu xảy ra theo thứ tự, có thể thay đổi và không cho phép trùng lặp.

Dữ liệu trong dictionary luôn được trình bày dưới dạng key-value và các cặp key-value đó không thể bị trùng lặp trong tập dữ liệu.

### **Tạo Dictionaries**

Dictionary có thể to hoặc nhỏ tùy thích. Hãy tạo một dictionary nhỏ dựa trên dữ liệu từ thị trường bất động sản Viet Nam để cung cấp cho chúng tôi một số thứ để làm việc.

Dictionary được viết bằng dấu ngoặc nhọn {}, với các cặp key-value trị bên trong. Mã cho một dictionary nhỏ trông như thế này:

In [15]:
vietnamdict = {
    "property_type": "house",
    "department": "luxury",
    "area": 235.0,
}
vietnamdict

{'property_type': 'house', 'department': 'luxury', 'area': 235.0}

#### **Thực hành**

Hãy thử nó cho mình! Tạo và in dictionary có tên hanoi với các cặp key-value trị "price_vnd": 121.555.09, "area_m2": 82.0 và "property_type": "house"

In [16]:
hanoi = {
    "price_vnd":"121.555.09",
    "area_m2": 82.0,
    "property_type": "house",
}
hanoi

{'price_vnd': '121.555.09', 'area_m2': 82.0, 'property_type': 'house'}

### **Làm việc với Dictionaries**

Sau khi tạo dictionary, có thể truy cập bất kỳ mục nào bằng cách sử dụng tên khóa của nó bên trong dấu ngoặc vuông.

Quay trở lại dictionary ví dụ của chúng ta, hãy truy cập giá trị cho "department".

In [17]:
x = vietnamdict["department"]
x

'luxury'

#### **Thực hành**

Truy cập giá trị price_vnd trong từ điểm hanoi đã tạo

Bạn cũng có thể dùng get để truy xuất một giá trị

In [18]:
x = vietnamdict.get("department")
x

'luxury'

#### **Thực hành**

Thử truy cập giá trị cho area_m2 bằng get và in kết quả

## **Dictionary Key**

Muốn biết các khóa có trong dictionary hoặc muốn lặp lại dictionary. Trong trường hợp như vậy, cần viết mã để truy cập tất cả các key-value trong dictionary bằng cách sử dụng phương thức **keys**:

In [19]:
vietnamdict.keys()

dict_keys(['property_type', 'department', 'area'])

Chuyển đổi đầu ra thành list:

In [20]:
list(vietnamdict.keys())

['property_type', 'department', 'area']

Bạn cũng có thể lặp qua cột dict.keys() mà không cần chuyển nó thành list:

In [21]:
for k in vietnamdict.keys():
    print(k)

property_type
department
area


#### **Thực hành**

in giá trị của mỗi key-value trong từ điển colomdict

In [38]:
for n in colomdict.items():
    print(n)

('property_type', 'house')
('department', 'quindio')
('area', 235.0)


## **JSON**

JSON là viết tắt của Java Script Object Notation, và nó là một định dạng văn bản để lưu trữ và vận chuyển dữ liệu.

**Làm việc với JSON**

JSON hoạt động bằng cách tạo các cặp key-value, trong đó key là dữ liệu có thể được biểu diễn bằng các chứa cái (được gọi là chuỗi). Values JSON có thể là strings, numbers, objects, arrays, boolean data, hoặc null. JSON thường xuất hiện dưới dạnh list các dictionary, như sau:

Dưới đây là ví dụ từ tập dữ liệu colombia-real-Estate-1 với hai cặp key-value đều bao gồm các giá trị string:

In [22]:
[
    {"property_type": "house", "department": "hanoi"},
    {"property_type": "house", "department": "hanoi"},
    {"property_type": "house", "department": "hanoi"},
]

[{'property_type': 'house', 'department': 'hanoi'},
 {'property_type': 'house', 'department': 'hanoi'},
 {'property_type': 'house', 'department': 'hanoi'}]

Dưới đây là ví dụ từ tập dữ liệu hanoi-real-Estate-1 với hai cặp key-value đều bao gồm các giá trị string:

In [23]:
{"property_type": "house", "department": "hanoi"}

{'property_type': 'house', 'department': 'hanoi'}

Các cặp JSON với các số:

In [24]:
{"area_m2": 187.0, "price_vnd": 330899.98}

{'area_m2': 187.0, 'price_vnd': 330899.98}

Khi kết hợp nhiều loại giá trị, nó trông như thế này:

In [25]:
{"property_type": "house", "price_vnd": 330899.98}

{'property_type': 'house', 'price_vnd': 330899.98}

### **References & Further Reading**9
- [A guide to basic math operations in Python](https://codingexplained.com/coding/python/basic-math-operators-in-python)
- [Python documentation on built-in data types](https://docs.python.org/3/library/stdtypes.html)
- [Summary of Python data types](https://www.w3schools.com/python/python_datatypes.asp)
- [Tutorial on type conversion in Python](https://www.datacamp.com/tutorial/python-data-type-conversion)
- [A description of how dictionaries work in Python](https://www.w3schools.com/python/python_dictionaries.asp)
- [An introduction to JSON](https://www.w3schools.com/js/js_json_syntax.asp)
- [An introduction to lists in Python](https://www.w3schools.com/python/python_lists.asp)
- [How to zip lists](https://www.adamsmith.haus/python/answers/how-to-zip-two-lists-in-python)
- [Calculating mean, median, and mode in Python](https://stackabuse.com/calculating-mean-median-and-mode-in-python/)
- [A brief tutorial of For Loops](https://www.w3schools.com/python/python_for_loops.asp)